### ISSUE TITLE
微信好友分享失败，多文件仅支持照片格式

### ISSUE THREAD

**Issue by zyjjfm** [shichaohui/WXShareMultiImage#10]
微信好友分享失败，多文件仅支持照片格式

**Comment by shichaohui** [comment]
Demo 是正常的，检查你的传参是否正确（如Bitmap是否正常），如果还是不行，提供一下你的代码、微信版本、手机系统信息。

**Comment by zyjjfm** [comment]
已经解决了，谢谢。我还有一个问题想问一下，源码中分享的进度条：
`val dialog = ProgressDialog(activity)
            dialog.setMessage("请稍候...")
            dialog.show()`
这个可以有参数控制是否显示吗？因为我的是先从网络上加载图片，然后分享，中间2个进度条先后显示不是特别好。

**Comment by zyjjfm** [comment]
> Demo 是正常的，检查你的传参是否正确（如Bitmap是否正常），如果还是不行，提供一下你的代码、微信版本、手机系统信息。

已经解决了，谢谢。我还有一个问题想问一下，源码中分享的进度条：
val dialog = ProgressDialog(activity) dialog.setMessage("请稍候...") dialog.show()
这个可以有参数控制是否显示吗？因为我的是先从网络上加载图片，然后分享，中间2个进度条先后显示不是特别好。

**Comment by shichaohui** [comment]
确实是这样。
因为接收到图片之后需要对图片进行一些处理，可能会耗时较长，所以加了那个对话框。
我想想怎么优化一下，如果你有好的方案，也可以提出来。

**Comment by zyjjfm** [comment]
> 确实是这样。
> 因为接收到图片之后需要对图片进行一些处理，可能会耗时较长，所以加了那个对话框。
> 我想想怎么优化一下，如果你有好的方案，也可以提出来。

可以在调用的方法中加入一个参数，来控制进度条是否显示嘛？这样灵活一点比较好，谢谢。

**Comment by shichaohui** [comment]
参考[首页文档](https://github.com/shichaohui/WXShareMultiImage)升级 [v1.0.9](https://github.com/shichaohui/WXShareMultiImage/releases)

**Comment by LiuJQ** [comment]
> 微信好友分享失败，多文件仅支持照片格式

请问这个问题是怎么解决的？
