### ISSUE TITLE
自动发表按钮怎么获取呢？

### ISSUE THREAD

**Issue by tiefeiniu** [shichaohui/WXShareMultiImage#11]
非常感谢楼主写的自动化发圈，非常有参考价值，另外我想请教下，就是最后一步，需要自己点击发表按钮才能最终发朋友圈，可不可以也自动点击发表按钮呢？

**Comment by shichaohui** [comment]
这个可以有，我这边可以加个可选项。
如果你急需这个功能，可以拉取代码，参考选图结束时模拟点击完成按钮的操作。
我这边完成该功能后会在这里回复你。

**Comment by tiefeiniu** [comment]
> 这个可以有，我这边可以加个可选项。
> 如果你急需这个功能，可以拉取代码，参考选图结束时模拟点击完成按钮的操作。
> 我这边完成该功能后会在这里回复你。

谢谢楼主，我这边是很需要这个功能，等您写好了，我再拉取，再次感谢！

**Comment by shichaohui** [comment]
完成了，按照[文档](https://github.com/shichaohui/WXShareMultiImage)升级到 [v1.0.8](https://github.com/shichaohui/WXShareMultiImage/releases) 版本即可。

**Comment by tiefeiniu** [comment]
> 完成了，按照文档升级到 v1.0.8 版本即可。

我拉去下来运行，自动发表还是没反应，试了两款手机都不行，微信都是最新版的

**Comment by shichaohui** [comment]
@tiefeiniu 
按照文档配置，必须 isAutoFill 和 isAutoPost 都为 true。

**Comment by tiefeiniu** [comment]
> @tiefeiniu
> 按照文档配置，必须 isAutoFill 和 isAutoPost 都为 true。

楼主有空的时候可以更下java 的么，我自己在java 里面添加，发现没效果  
        if (ShareInfo.getInstance().getWaitingImageCount() > 0) {
            AccessibilityNodeInfo gridView = findNodeInfo(rootNodeInfo, GridView.class.getName());
            if (gridView != null && gridView.getChildCount() > 2) {
                gridView.getChild(1).performAction(AccessibilityNodeInfo.ACTION_CLICK);
            }
        } else if (true) {
            List<AccessibilityNodeInfo> list = getRootInActiveWindow().findAccessibilityNodeInfosByText("发表");
            performClickBtn(list);
        }

**Comment by shichaohui** [comment]
不只是这段代码，还要改点其他东西，选图完成返回朋友圈界面的时候，收到的事件是在刚进入朋友圈时就处理过的，因此过滤掉了。你先用依赖或者拉 kt 的代码，我暂时没空改 Java 的代码。

**Comment by tiefeiniu** [comment]
> 不只是这段代码，还要改点其他东西，选图完成返回朋友圈界面的时候，收到的事件是在刚进入朋友圈时就处理过的，因此过滤掉了。你先用依赖或者拉 kt 的代码，我暂时没空改 Java 的代码。

我大概明白了，我再试试

**Comment by tiefeiniu** [comment]
> 不只是这段代码，还要改点其他东西，选图完成返回朋友圈界面的时候，收到的事件是在刚进入朋友圈时就处理过的，因此过滤掉了。你先用依赖或者拉 kt 的代码，我暂时没空改 Java 的代码。
> 
> 我大概明白了，我再试试
我这边java 的弄好了，后续我再研究 怎么分享纯文字和视频
