### ISSUE TITLE
自动打开相册是报错

### ISSUE THREAD

**Issue by tiefeiniu** [shichaohui/WXShareMultiImage#12]
报了这个错，
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.accessibility.AccessibilityNodeInfo.performAction(int)' on a null object reference
        at com.sch.share.WXShareMultiImageService.openAlbum(WXShareMultiImageService.java:186)
        at com.sch.share.WXShareMultiImageService.onAccessibilityEvent(WXShareMultiImageService.java:76)

麻烦楼主看看

**Comment by shichaohui** [comment]
我记得你是自己参考 Kotlin 版本改的 Java 版，我们代码已经不一样，你的问题要自己解决。
错误日志已经描述的很清楚了，WXShareMultiImageService.java 的 186 行，执行 performAction() 函数的对象为 null。

**Comment by tiefeiniu** [comment]
> 我记得你是自己参考 Kotlin 版本改的 Java 版，我们代码已经不一样，你的问题要自己解决。
> 错误日志已经描述的很清楚了，WXShareMultiImageService.java 的 186 行，执行 performAction() 函数的对象为 null。
代码是不一样了，我用的是网络图片，应该是图片过大的问题，压缩下就可以

**Comment by shichaohui** [comment]
应该与图片关系不大，你对比代码看看哪里的逻辑有问题。
