### ISSUE TITLE
新版微信分享弹出选择照片，而不是自动选择照片

### ISSUE THREAD

**Issue by fxxkscript** [shichaohui/WXShareMultiImage#15]

**Comment by shichaohui** [comment]
用的是 [1.1.0](https://github.com/shichaohui/WXShareMultiImage/releases) 版本吗？

**Comment by fxxkscript** [comment]
> 用的是 [1.1.0](https://github.com/shichaohui/WXShareMultiImage/releases) 版本吗？

是的，会弹出相册选图的。

然后，有些安卓手机，特定某个型号，分享到朋友圈只有一个图片，剩下的出不来

**Comment by shichaohui** [comment]
停留在哪个步骤？底部弹窗还是选择图片页面？

**Comment by fxxkscript** [comment]
![WechatIMG21](https://user-images.githubusercontent.com/1597584/70516511-16be1880-1b72-11ea-8f61-c0feddb4e01a.jpeg)

点击从相册选择，才能自动走下去

**Comment by v42cmx** [comment]
微信版本 7.0.9
小米 9 安卓 10.0
分享时文字丢失
点击从相册选择，才能自动走下去

微信版本 7.0.9
小米MIX 2 
点击从相册选择，才能自动走下去

**Comment by shichaohui** [comment]
文字丢失应该是 Android Q 剪切板权限的问题，我稍后修改一下。
我的手机（HUAWEI P30 微信 v7.0.9）上可以正常选图啊。你自己拉代码调试看看。

**Comment by v42cmx** [comment]
HUAWEI P30 PRO 微信 v7.0.9
我们试过，可以的

**Comment by shichaohui** [comment]
这就尴尬了

**Comment by shichaohui** [comment]
我手头的设备都没有问题，你拉代码调调看，可能是无障碍事件处理的兼容不够。

**Comment by shichaohui** [comment]
@fxxkscript 解决了没有啊？

**Comment by fxxkscript** [comment]
> @fxxkscript 解决了没有啊？

还没有，我是用flutter调用的，Kotlin/Java并不太熟悉，还没去调

**Comment by fxxkscript** [comment]
@shichaohui 我发现用你的demo是没有问题，但是我包了网络图下载之后就回出现这个问题

**Comment by shichaohui** [comment]
不会是图片来源的问题，不管图片是怎么来的，最终都是要转成 Bitmap 或者 File 传进去的，在传进去之前和库本身都是无关的。（我也加载过网图，没有这样的问题的）
走到弹窗进行不下去了，手动点击选图进入图片列表又能自动选择，这个明显是弹窗显示出来时没有检测到相应的事件（或者有事件但是没有找到相应的 View ，导致模拟点击失败），从而无法进行下一步。
最好是重现一下，调试看看出问题的时候哪一步执行除了问题。

**Comment by fxxkscript** [comment]
@shichaohui 
弹窗打开，我这里debug，发现是android.widget.FrameLayout

![image](https://user-images.githubusercontent.com/1597584/70962265-7dd25480-20bf-11ea-8a98-6ae72c8efbb5.png)

**Comment by fxxkscript** [comment]
@shichaohui 

我把`BaseShare.kt` 中的`import android.support.v4.content.ContextCompat` 改成 `import androidx.core.content.ContextCompat` 就可以了，难道是AndroidX的原因？

**Comment by shichaohui** [comment]
确实是 AndroidX 的问题。
项目里有字符串常量 `"android.support.v7.widget.RecyclerView"`，在 AndroidX 的项目里被转换成了 `androidx.recyclerview.widget.RecyclerView` ，所以事件检测一直通不过，`openAlbum(event) ` 也就不会执行。
已经在 [v1.1.2](https://github.com/shichaohui/WXShareMultiImage/releases) 解决了，更新一下就好。
