### ISSUE TITLE
图片分享 顺序会乱掉

### ISSUE THREAD

**Issue by pengjunhong** [shichaohui/WXShareMultiImage#17]

**Comment by shichaohui** [comment]
分享朋友圈有做排序处理的，不会乱序。
分享好友乱序是正常的，因为图片是同时发送的，但是不会同时到达，所以没必要处理顺序。

**Comment by pengjunhong** [comment]
希望作者可以多测试几遍 就是分享朋友圈，使用demo我这边有时候都可以模拟出1加载了2次 挺容易复现的就是多发几遍就有了。

**Comment by will-zhang** [comment]
> 希望作者可以多测试几遍 就是分享朋友圈，使用demo我这边有时候都可以模拟出1加载了2次 挺容易复现的就是多发几遍就有了。

我也有同样的问题，你解决了么？
