### ISSUE TITLE
关于微信分享给好友使用Uri.fromFile的疑问

### ISSUE THREAD

**Issue by ZhaoxiZhang** [shichaohui/WXShareMultiImage#18]
场景：分享图片给好友
你好，我想请问一下在 Android N 以上不是禁止通过 file:// 跨app分享文件了吗，并且需要使用 FileProvider 方式来进行跨 app 分享文件，想请问下通过 Uri.fromFile 方式还能分享图片到微信的原因

**Comment by lanhaoxiang** [comment]
https://github.com/shichaohui/WXShareMultiImage/blob/master/wx-share/src/main/java/com/sch/share/manager/FileManager.kt#L20
