### ISSUE TITLE
微信分享多图时选不到图片，只是偶尔可以

### ISSUE THREAD

**Issue by atari456** [shichaohui/WXShareMultiImage#19]
微信分享多图时选不到图片，只是偶尔可以。没有改任何代码直接编译。

还有就是无障碍每次都要打开。 设置为打开后，重启手机。 首次打开app可以，后续又自动关掉了。

**Comment by shichaohui** [comment]
选不到图的问题还要再看看。
重启 APP 无障碍被关闭是 Android 系统的问题，我也处理不来。

**Comment by shichaohui** [comment]
分享方案已更新，请更新到最新版本。
