### ISSUE TITLE
开启无障碍服务后，多图分享到朋友圈时，有一定的概率不会自动选图

### ISSUE THREAD

**Issue by ninety19** [shichaohui/WXShareMultiImage#2]
如题，debug查看后发现findNodeInfo(AccessibilityNodeInfo rootNodeInfo, String className)这个方法有时候返回值会为null，从而导致程序中断执行了。
比如说选择图片时执行到
 AccessibilityNodeInfo gridView = findNodeInfo(rootNodeInfo, GridView.class.getName());
gridView取值有时候会为null导致程序中断了，后面要自己手动选择照片。
请问这个有什么方法可以避免吗？
另外请教一个题外话题，如下图，这个应该是android的系统分享功能，我按照您的这篇分享添加了多图分享到朋友圈的功能，但是如红框中标示的名称不知道怎么自定义，不知道您能提供帮助，谢谢了。
![image](https://user-images.githubusercontent.com/17473472/50063150-ff11b580-01e5-11e9-978b-9b718fb73efb.png)

**Comment by shichaohui** [comment]
findNodeInfo() 返回 null 的问题暂时没有解决。
“多图转发新版朋友圈”是通过给 Activity 添加 <intent-filter> 加上的吗？如果是的话，可以给 activity 标签增加属性（name、label）就行了，没有设置时默认使用 application 的同名属性。
```
<activity
        android:name=".MyActivity"
        android:icon="@mipmap/img"
        android:label="Label">
        ...
</activity>
```

**Comment by shichaohui** [comment]
Intent 被用来调起微信内部分享的 Activity，不会显示系统分享面板的。
你要给系统的分享面板里添加分享按钮，要用这个方式，这样其他APP调用系统分享时就能看到你的 Activity。
```
<activity
    android:name=".MyShareActivity"
    android:icon="@mipmap/img"
    android:label="Label">
    <intent-filter>
        <action android:name="android.intent.action.SEND"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <data android:mimeType="image/*"/><!--可增加文件类型-->
    </intent-filter>
</activity>
```

**Comment by shichaohui** [comment]
这种方式只是启动微信的分享 Activity  吧，怎么会进入系统的分享界面呢？

**Comment by ninety19** [comment]
> 这种方式只是启动微信的分享 Activity 吧，怎么会进入系统的分享界面呢？

是我表述不够全，而且代码也没贴全
` Intent intent = new Intent();
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
        intent.setType("image/*");
        intent.setAction(Intent.ACTION_SEND_MULTIPLE);
        intent.putParcelableArrayListExtra(Intent.EXTRA_STREAM, uris);
        Intent chooser = Intent.createChooser(intent, "选择分享");`
这种方式启动系统分享，然后再额外又启动一个微信朋友圈的。

不过在您的提示下我自定义一个Activity再添加<intent-filter> 已经解决问题了。

**Comment by zhouwei1988** [comment]
微信7.0分享图片报资源获取失败

**Comment by shichaohui** [comment]
@zhouwei1988 
刚更新了 Java 版的代码，kotlin 还没有更新，发新包再通知你。

**Comment by zhouwei1988** [comment]
这个兼容7.0只是把图片下载到本地然后提示用户在相册里面选择图片，并没有直接把图片带过去吧

**Comment by shichaohui** [comment]
@zhouwei1988 开启无障碍服务，跳转到微信后自动模拟用户操作 [发现-朋友圈-分享-选图]。仅对微信一级页面有效，子页面需要用户手动退回到一级页面触发自动分享。
