### ISSUE TITLE
android Q 适配问题

### ISSUE THREAD

**Issue by wuzhongyuan** [shichaohui/WXShareMultiImage#20]
targetSDKVersion升级到29后，FileManager类的getTmpFileDir函数会调用 val parent = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)；导致FileManager类中clearTmpFile函数执行fileDir.listFiles()会返回null，导致自动选图失败。

**Comment by shichaohui** [comment]
已修复，更新 [v1.1.4](https://github.com/shichaohui/WXShareMultiImage/releases/tag/v1.1.4) 即可
