### ISSUE TITLE
获取资源失败，无法分享到朋友圈

### ISSUE THREAD

**Issue by GodOfSP** [shichaohui/WXShareMultiImage#3]
微信7.0  不管开不开无障碍
![screenshot_20190123_112329_com sch share demo](https://user-images.githubusercontent.com/15963152/51581008-6b788680-1f01-11e9-9a3a-2d3f433965c9.jpg)

**Comment by ltg1308101101** [comment]
我也是一样，根本跑不起来的demo

**Comment by shichaohui** [comment]
微信 7.0？代码里微信 7.0 以上没有调用任何分享 API，仅仅是打开微信 APP，打开 APP 后，
if (开了无障碍) {
    通过模拟点击选图进入图文分享
} else {
    提醒用户手动分享
}
这个逻辑，不会出现获取资源失败的问题的。
如果你的手机上确实有问题，那么拉代码自己调试一下吧，我重新不了。

**Comment by shichaohui** [comment]
刚刚发布了 v1.0.7 ，降低了分享的复杂度，并优化了系统及设备兼容性。
