### ISSUE TITLE
大佬你好,9.0启动以后进入朋友圈无法自动分享

### ISSUE THREAD

**Issue by q735510971** [shichaohui/WXShareMultiImage#5]
大佬你好,我现在遇到的问题是在Android9.0以后现在已知的是所有手机最多能自动分享一次到最后的为你选好照片等待发布.
之后所有的手机都出现了打开朋友圈然后弹出拍摄和从相册选择 这个POPwd,甚至 会直接只走到微信主页然后就停止了,求大佬们给一点方案.或者拉我进个群也行(WX,QQ 735510971)谢谢

**Comment by shichaohui** [comment]
刚刚发布了 v1.0.7 ，降低了分享的复杂度，并优化了系统及设备兼容性。
