### ISSUE TITLE
项目集成运行时 错误: 找不到kotlin.jvm.functions.Function1的类文件

### ISSUE THREAD

**Issue by saga87** [shichaohui/WXShareMultiImage#7]
普通android项目  implementation 'com.sch.share:wx-share:1.0.6'
WXShareMultiImageHelper.isServiceEnabled(context)

错误: 无法访问Function1
找不到kotlin.jvm.functions.Function1的类文件

**Comment by shichaohui** [comment]
没有遇到过这个问题呢，你试试修改 Gradle 版本、clean 等方式能不能解决。

**Comment by BryceLee** [comment]
kotlin插件配置一下，可以参考源代码设置～

**Comment by GitHubKlod** [comment]
这个问题解决了吗  我也遇到了

**Comment by BryceLee** [comment]
@GitHubKlod  kottlin 插件的问题，参考源代码配置以下就可以了，我一开始也遇到
