### ISSUE TITLE
无障碍服务权限开启，但是不自动发布

### ISSUE THREAD

**Issue by BryceLee** [shichaohui/WXShareMultiImage#8]
微信7.0.4;
Demo正常运行；
集成项目后，
辅助功能中已经开启自定义的无障碍服务，但是总是走这个逻辑
自动跳转微信，并提示用户打开朋友圈粘贴文字选择图片。
请问这可能是什么原因？

**Comment by BryceLee** [comment]
设置中已经开启，但是现象看，就是没开启，而且每次调用分享都会让自己去授权。

**Comment by BryceLee** [comment]
发现是在WXShareMultiImageHelper.isServiceEnabled()方法里，判断是否注册服务的时候出错了

**Comment by shichaohui** [comment]
1. 这个问题好像是系统的问题，有时候需要重启手机才能解决。
2. 刚刚发布了 v1.0.7 ，降低了分享的复杂度，并优化了系统及设备兼容性。有兴趣可以试试。

**Comment by BryceLee** [comment]
好的 谢谢
